# Generated by Django 4.1.7 on 2023-02-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_unitconversionratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='unitcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
