# Generated by Django 4.1.7 on 2023-02-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_source_recipe_source_url_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientgroup',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.ingredientgroup'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
