# Generated by Django 4.1.7 on 2023-02-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_ingredient_ingredientgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.ingredientgroup'),
        ),
    ]
