# Generated by Django 4.1.7 on 2023-02-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_unitcategory_ingredientgroup_amount_recipe_portions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='UnitCategory',
        ),
    ]
