# Generated by Django 4.1.7 on 2023-02-24 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_delete_unit_delete_unitcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_ingredients', to='recipes.ingredientgroup'),
        ),
    ]
